#!/usr/bin/env python3
"""Generate the daily 宜忌 strings and their 1-bit LVGL font.

The strings are the complete 宜 / 忌 lists from ``lunar_python``, joined with
``、``, matching the 宜 / 忌 columns of auspicious_days_2026_2030.csv.  The
dashboard shows only as much of each as fits one line, so the table carries the
whole list rather than the first entry alone.

The same face also carries the fixed Chinese the dashboard prints: the 十二建除
and 十二值神 labels and the twelve names each can take.

Run it with ``--from-csv`` to build both assets from the checked-in CSV instead
of ``lunar_python``; the CSV and this script's output describe the same days."""
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from lunar_utils import CSV_PATH, DAY_DEITIES, HEAVENLY_OFFICERS, all_days, load_csv

OUT = Path(__file__).resolve().parents[1] / "components/ui_bsp/page_calendar"

# The 建除 / 值神 labels, the space that separates them on the dashboard's single
# status line, and every name either of them can print.
ALMANAC_LABELS = " 十二建除值神：" + "".join(HEAVENLY_OFFICERS) + "".join(DAY_DEITIES)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from-csv", action="store_true",
                        help="read the day table from the CSV instead of lunar_python")
    parser.add_argument("--csv", type=Path, default=CSV_PATH,
                        help="table to read with --from-csv")
    args = parser.parse_args()
    days = load_csv(args.csv) if args.from_csv else all_days()
    texts = [("、".join(yi) if yi else "无", "、".join(ji) if ji else "无")
             for _, _, _, _, yi, ji in days]
    blob = bytearray(); offsets = []
    for yi, ji in texts:
        offsets.append(len(blob)); blob.extend(yi.encode()); blob.append(0); blob.extend(ji.encode()); blob.append(0)
    # 12 entries per line — the wrapping lunar_auspicious_days.h uses. Written as a
    # few very long rows this file is a ~1.7 MB single line that no diff can show.
    values = ",\n    ".join(", ".join(str(x) for x in offsets[i:i + 12])
                             for i in range(0, len(offsets), 12))
    escaped = ",\n    ".join(", ".join(f"0x{x:02X}" for x in blob[i:i + 12])
                             for i in range(0, len(blob), 12))
    (OUT / "lunar_yiji_data.h").write_text(
        "#pragma once\n#include <stdint.h>\n"
        "static const uint32_t lunar_yiji_offsets[] = {\n    " + values + "\n};\n"
        "static const unsigned char lunar_yiji_text[] = {\n    " + escaped + "\n};\n"
        "static inline const char *lunar_yi(int i) { return (const char *)&lunar_yiji_text[lunar_yiji_offsets[i]]; }\n"
        "static inline const char *lunar_ji(int i) { const char *p=lunar_yi(i); while(*p++) {} return p; }\n", encoding="utf-8")
    chars = sorted(set("宜忌：无" + ALMANAC_LABELS + "".join(a+b for a,b in texts)))
    font = ImageFont.truetype("/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc", 12, index=2)
    # LVGL reads a 1 bpp glyph as one MSB-first bit stream with a row stride of
    # box_w bits: rows are not padded to a byte boundary, so a 12 px glyph is a
    # 14 x 12 = 168 bit (21 byte) run. Padding each row out to two bytes desyncs
    # the decoder by four bits per row and renders the glyph as garbage.
    bitmap=[]
    for ch in chars:
        im=Image.new("1",(12,14)); ImageDraw.Draw(im).text((0,-2),ch,font=font,fill=1)
        row_bits=[1 if im.getpixel((x,y)) else 0 for y in range(14) for x in range(12)]
        for i in range(0,len(row_bits),8):
            b=0
            for bit in row_bits[i:i+8]: b=(b<<1)|bit
            bitmap.append(b)
    base=ord(chars[0]); deltas=[ord(c)-base for c in chars]
    # LVGL looks up glyph_dsc[glyph_id_start + index] with glyph_id_start = 1,
    # so index 0 must stay the empty placeholder lv_font_conv emits.
    desc = ("{.bitmap_index=0,.adv_w=0,.box_w=0,.box_h=0,.ofs_x=0,.ofs_y=0},\n"
            + ",\n".join(f"{{.bitmap_index={i*21},.adv_w=192,.box_w=12,.box_h=14,.ofs_x=0,.ofs_y=-2}}"
                         for i in range(len(chars))))
    bits=", ".join(f"0x{x:02X}" for x in bitmap); uni=", ".join(f"0x{x:X}" for x in deltas)
    (OUT / "fonts/lv_font_calendar_yiji_12.c").write_text(f'''/* 12 px 1 bpp Noto Sans CJK subset for the dashboard's Chinese: every 宜/忌
 * entry of 2026--2030 plus the fixed 建除/值神 labels and names ({len(chars)} glyphs).
 * Generated by lunar/generate_ui_yiji.py; do not edit manually.
 * LVGL reads a 1 bpp glyph as one MSB-first bit stream with a row stride of
 * box_w bits, so each 12 x 14 glyph is 21 contiguous bytes. */
#include "lvgl.h"
static const uint8_t glyph_bitmap[]={{ {bits} }};
/* Index 0 is the empty placeholder lv_font_conv emits: LVGL indexes
   glyph_dsc[glyph_id_start + ofs], and glyph_id_start is 1. */
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[]={{ {desc} }};
static const uint16_t unicode_list[]={{ {uni} }};
static const lv_font_fmt_txt_cmap_t cmaps[]={{ {{.range_start=0x{base:X},.range_length=0x{deltas[-1]+1:X},.glyph_id_start=1,.unicode_list=unicode_list,.list_length={len(chars)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}} }};
static lv_font_fmt_txt_glyph_cache_t cache; static const lv_font_fmt_txt_dsc_t dsc={{.glyph_bitmap=glyph_bitmap,.glyph_dsc=glyph_dsc,.cmaps=cmaps,.cmap_num=1,.bpp=1,.cache=&cache}};
const lv_font_t lv_font_calendar_yiji_12={{.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=14,.base_line=2,.dsc=&dsc}};
''',encoding="utf-8")
    print(f"wrote lunar_yiji_data.h and lv_font_calendar_yiji_12.c "
          f"({len(chars)} glyphs, {len(texts)} days)")
if __name__ == "__main__": main()
